/*
 * File: app/view/ListContainer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('CityBars.view.ListContainer', {
    extend: 'CityBars.view.ui.ListContainer',
    alias: 'widget.listcontainer',

    initialize: function() {
        var me = this;
        me.callParent(arguments);
    }

});