/*
 * File: app/model/Business.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CityBars.model.Business', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'name'
            },
            {
                name: 'latitude'
            },
            {
                name: 'longitude'
            },
            {
                name: 'address1'
            },
            {
                name: 'address2'
            },
            {
                name: 'address3'
            },
            {
                name: 'phone'
            },
            {
                name: 'state_code'
            },
            {
                name: 'mobile_url'
            },
            {
                name: 'rating_img_url_small'
            },
            {
                name: 'photo_url'
            }
        ]
    }
});