/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({

    requires: [
        'Ext.dataview.List',
        'Ext.data.proxy.JsonP'
    ],
    models: [
        'Business'
    ],
    stores: [
        'BusinessStore'
    ],
    views: [
        'DetailPanel',
        'ListContainer',
        'MainNav'
    ],
    name: 'CityBars',
    controllers: [
        'Business'
    ],

    launch: function() {

        Ext.create('CityBars.view.MainNav', {fullscreen: true});
    }

});
